# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class URLStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/api.URL/register',
        request_serializer=message__pb2.UrlRequest.SerializeToString,
        response_deserializer=message__pb2.UrlResponse.FromString,
        )


class URLServicer(object):
  """The greeting service definition.
  """

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_URLServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=message__pb2.UrlRequest.FromString,
          response_serializer=message__pb2.UrlResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.URL', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
